### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by m4l3z** [christophhart/HISE#15]
hello there ! 

After installing the dependencies and cloning the repo, I was unable to run properly Projucer. 
```
(gdb) run
Starting program: /home/m4l3z/HISE/tools/projucer/Projucer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
JUCE v4.3.0

Program received signal SIGILL, Illegal instruction.
0x00000000006ebcdc in juce::AffineTransform::AffineTransform (
    this=0xdbed90 <juce::AffineTransform::identity>)
    at ../../../../modules/juce_graphics/geometry/juce_AffineTransform.cpp:27
27	../../../../modules/juce_graphics/geometry/juce_AffineTransform.cpp: No such file or directory

```
```

(gdb) backtrace
#0  0x00000000006ebcdc in juce::AffineTransform::AffineTransform (
    this=0xdbed90 <juce::AffineTransform::identity>)
    at ../../../../modules/juce_graphics/geometry/juce_AffineTransform.cpp:27
#1  0x00000000007669ae in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535)
    at ../../../../modules/juce_graphics/geometry/juce_AffineTransform.cpp:83
#2  0x0000000000766a3c in _GLOBAL__sub_I__ZN4juce6ColourC2Ev ()
    at ../../../../modules/juce_graphics/juce_graphics.cpp:164
#3  0x000000000092189d in __libc_csu_init ()
#4  0x00007ffff61017bf in __libc_start_main (
    main=0x4391f7 <main(int, char**)>, argc=1, argv=0x7fffffffddd8, 
    init=0x921850 <__libc_csu_init>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffddc8)
    at ../csu/libc-start.c:247
#5  0x0000000000408709 in _start ()
```

**Comment by qdr** [comment]
Hi m4l3z, 

do you get the same issues with a new (original) JUCE install? 
https://www.juce.com/get-juce 

Greets,
qdr

**Comment by m4l3z** [comment]
Something seems wrong with their server, I tried to download it several times over the last days and never was able to get through even tho my connection is fair.  I'll keep trying. 
I have a unrelated question (sorry) Are native linux plugins planning to be implemented (lv2 maybe) ? 
I think it's the OS that could benefit the most from your work.

Thanks,

**Comment by christophhart** [comment]
You can also get the JUCE code from Github:

https://github.com/julianstorer/JUCE

As for native plugins, JUCE does support native VST plugins and some folks seem to have successfully built and loaded HISE it into a DAW on Ubuntu (REAPER IIRC).

**Comment by m4l3z** [comment]
So I managed to compile Juce. Worked fine. Saved the project. 
When I try to compile HISE I had a fatal error 
```
Compiling juce_audio_devices.cpp
In file included from ../../JuceLibraryCode/juce_audio_devices.cpp:9:0:
../../../../JUCE/modules/juce_audio_devices/juce_audio_devices.cpp:119:25: fatal error: jack/jack.h: No such file or directory
   #include <jack/jack.h>
                         ^

```

I use libjack2 on my computer and going back to libjack causes a lot of problems on my system (I already tried it for some other program I tried to compile) so I guess I won't be able to compile it.

**Comment by trebmuh** [comment]
You need a -dev package for jack. If you're under a debian or debian-related distribution, the package you need is named "libjack-dev".

**Comment by trebmuh** [comment]
@m4l3z : you need a -dev package for jack. If you're under a debian or debian-related distribution, the package you need is named "libjack-dev".

**Comment by qdr** [comment]
Jep,

on xubuntu here,, : it works after installing "libjack-dev" ;)
greets, d

2017-01-15 14:42 GMT+01:00 Olivier Humbert <notifications@github.com>:

**Comment by m4l3z** [comment]
Yes I know but 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libjack-dev : Depends: libjack0 (= 2:0.124.2~20151211-2~kxstudio1v5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
```
sudo apt-get install libjack0 libjack-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cadence-data cadence-tools catarina catia liblo7:i386 libtag1v5:i386 python3-pyqt4 rtirq-init
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  jackd1 libdbus-1-dev libzita-alsa-pcmi0 libzita-resampler1
Recommended packages:
  jackd1-firewire
The following packages will be REMOVED:
  cadence claudia gstreamer0.10-plugins-good:i386 ia32-libs jackd jackd2 jamin kxstudio-meta-all kxstudio-meta-audio
  kxstudio-meta-audio-plugins ladish libasound2-plugins:i386 libfluidsynth1:i386 libjack-jackd2-0
  libjack-jackd2-0:i386 libportaudio2:i386 libsdl-mixer1.2:i386 nyquist:i386 rakarrack


```

I'm loosing a lot of softwares by installing this lib.

**Comment by trebmuh** [comment]
what's about installing "libjack-jackd2-dev" ?

**Comment by m4l3z** [comment]
@trebmuh haha it does work, thanks. I feel especially stupid because it's how I solved it last time I had this problem..

**Comment by trebmuh** [comment]
Glad it works.
