### ISSUE TITLE
projucer not executable / invalid machine command

### ISSUE THREAD

**Issue by toxonic75** [christophhart/HISE#151]
I've got a problem with the precompiled Projucer binary shipped with HISE on Linux Mint 19.2. 
I get the following error message when i try to execute it via terminal:
`Illegal instruction (core dumped)`
It occurs with all Projucer binaries that come with HISE, independent from the HISE branch.
Can someone help?

**Comment by toxonic75** [comment]
i managed it to find the core dump via coredumpctl and analyze them in gdb with "thread apply all bt". but i have no experience with coding and debugging, so the results are not very useful for me. is there anyone, who can tell me, what the following lines mean:
`toxonic@toxonic-studio:~/Schreibtisch$ coredumpctl gdb 503
           PID: 503 (Projucer)
           UID: 1000 (toxonic)
           GID: 1000 (toxonic)
        Signal: 4 (ILL)
     Timestamp: Mon 2019-12-09 13:48:29 CET (55s ago)
  Command Line: /home/toxonic/Schreibtisch/Projucer
    Executable: /home/toxonic/Schreibtisch/Projucer
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (toxonic)
       Boot ID: e87925fce2cd47049b7ca123888c23e8
    Machine ID: f3d85c83fd6e458aba76dbf56f683032
      Hostname: toxonic-studio
       Storage: /var/lib/systemd/coredump/core.Projucer.1000.e87925fce2cd47049b7ca123888c23e8.503.1575895709000000.lz4
       Message: Process 503 (Projucer) of user 1000 dumped core.
                
                Stack trace of thread 503:
                #0  0x000000000084e149 n/a (/home/toxonic/Schreibtisch/Projucer)
                #1  0x000000000084e229 n/a (/home/toxonic/Schreibtisch/Projucer)
                #2  0x0000000000a3ad1d n/a (/home/toxonic/Schreibtisch/Projucer)

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/toxonic/Schreibtisch/Projucer...(no debugging symbols found)...fertig.
[New LWP 503]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/toxonic/Schreibtisch/Projucer'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000000000084e149 in __static_initialization_and_destruction_0 ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7f4875375280 (LWP 503)):
#0  0x000000000084e149 in _Z41__static_initialization_and_destruction_0ii ()
#1  0x000000000084e229 in _GLOBAL__sub_I__ZNK4juce6ColoureqERKS0_ ()
#2  0x0000000000a3ad1d in __libc_csu_init ()
#3  0x00007f486fa6cb28 in __libc_start_main (main=0x43938b <main>, argc=1, argv=0x7ffe60d51788, init=0xa3acd0 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe60d51778) at ../csu/libc-start.c:266
#4  0x000000000040b7c9 in _start ()
(gdb) 
`

**Comment by davidhealey** [comment]
What CPU do you have?

**Comment by toxonic75** [comment]
lscpu says:
```
toxonic@toxonic-studio:~/Schreibtisch$ lscpu
Architektur:                   x86_64
CPU Operationsmodus:           32-bit, 64-bit
Byte-Reihenfolge:              Little Endian
CPU(s):                        4
Liste der Online-CPU(s):       0-3
Thread(s) pro Kern:            1
Kern(e) pro Socket:            4
Sockel:                        1
NUMA-Knoten:                   1
Anbieterkennung:               AuthenticAMD
Prozessorfamilie:              18
Modell:                        1
Modellname:                    AMD A8-3870 APU with Radeon(tm) HD Graphics
Stepping:                      0
CPU MHz:                       879.947
Maximale Taktfrequenz der CPU: 3000,0000
Minimale Taktfrequenz der CPU: 800,0000
BogoMIPS:                      5992.62
Virtualisierung:               AMD-V
L1d Cache:                     64K
L1i Cache:                     64K
L2 Cache:                      1024K
NUMA-Knoten0 CPU(s):           0-3
Markierungen:                  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
```

**Comment by davidhealey** [comment]
Can you provide the output of this command in the terminal inxi -Fxz

Just your desktop for now, we'll worry about your laptop later.

**Comment by toxonic75** [comment]
yeah, here it is:
```
System:
  Host: toxonic-studio Kernel: 4.15.0-72-generic x86_64 bits: 64 
  compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.2.4 
  Distro: Linux Mint 19.2 Tina base: Ubuntu 18.04 bionic 
Machine:
  Type: Desktop Mobo: ASUSTeK model: F1A55-M LK R2.0 v: Rev X.0x 
  serial: <filter> BIOS: American Megatrends v: 0501 date: 05/31/2012 
CPU:
  Topology: Quad Core model: AMD A8-3870 APU with Radeon HD Graphics 
  bits: 64 type: MCP arch: Fusion L2 cache: 4096 KiB 
  flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 23970 
  Speed: 943 MHz min/max: 800/3000 MHz Core speeds (MHz): 1: 943 2: 965 
  3: 968 4: 1440 
Graphics:
  Device-1: AMD BeaverCreek [Radeon HD 6550D] vendor: ASUSTeK driver: radeon 
  v: kernel bus ID: 00:01.0 
  Display: x11 server: X.Org 1.19.6 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: AMD SUMO (DRM 2.50.0 / 4.15.0-72-generic LLVM 8.0.0) 
  v: 3.3 Mesa 19.0.8 direct render: Yes 
Audio:
  Device-1: AMD FCH Azalia vendor: ASUSTeK driver: snd_hda_intel v: kernel 
  bus ID: 00:14.2 
  Device-2: Focusrite-Novation type: USB driver: snd-usb-audio bus ID: 1-4:9 
  Device-3: Midiman type: USB driver: snd-usb-audio bus ID: 5-3:3 
  Sound Server: ALSA v: k4.15.0-72-generic 
Network:
  Device-1: Qualcomm Atheros AR9287 Wireless Network Adapter driver: ath9k 
  v: kernel port: f100 bus ID: 02:00.0 
  IF: wlp2s0 state: up mac: <filter> 
  Device-2: Qualcomm Atheros AR8161 Gigabit Ethernet vendor: ASUSTeK 
  driver: alx v: kernel port: e000 bus ID: 03:00.0 
  IF: enp3s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 931.51 GiB used: 91.53 GiB (9.8%) 
  ID-1: /dev/sda vendor: Toshiba model: DT01ACA100 size: 931.51 GiB 
Partition:
  ID-1: / size: 217.89 GiB used: 20.37 GiB (9.4%) fs: ext4 dev: /dev/sda6 
  ID-2: /home size: 347.43 GiB used: 71.15 GiB (20.5%) fs: ext4 
  dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 18.8 C mobo: N/A gpu: radeon temp: 21 C 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 241 Uptime: 8h 41m Memory: 7.26 GiB used: 2.84 GiB (39.1%) 
  Init: systemd runlevel: 5 Compilers: gcc: 7.4.0 clang: 6.0.0-1ubuntu2 
  Shell: bash v: 4.4.20 inxi: 3.0.32 
```

**Comment by davidhealey** [comment]
I suspected this might be the case 

> flags: lm nx pae sse sse2 sse3 sse4a

Your CPU is too old for this build of Projucer, it needs to support sse4_1

Now let's run the same command for your Intel laptop. I'd be surprised if an i5 didn't support sse4.1 but you never know.

**Comment by toxonic75** [comment]
okay, that's quite confusing, since the Projucer that i built with the newest JUCE Huckelberry works on my machine. it problem only occurs with the Projucr shipped with HISE. Nevertheless, here's the output of my laptops terminal, and indeed it supports sse4_1 and sse4_2, but the Projucer from the HISE repo doesn't work here too...
```
System:    Host: toxonic-Satellite-L500 Kernel: 4.15.0-72-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 Distro: Linux Mint 19.2 Tina base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: TOSHIBA product: Satellite L500 v: PSLS9E-02800CGR serial: <filter> 
           Mobo: TOSHIBA model: NSWAA v: 1.00 serial: <filter> UEFI [Legacy]: TOSHIBA v: 1.60 date: 03/02/10 
Battery:   ID-1: BAT1 charge: 48.5 Wh condition: 48.5/56.2 Wh (86%) model: COMPAL PA5024U-1BRS status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i5 M 430 bits: 64 type: MT MCP arch: Nehalem rev: 2 L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 18087 
           Speed: 1450 MHz min/max: 1199/2267 MHz Core speeds (MHz): 1: 1450 2: 1401 3: 1461 4: 1484 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] RV730/M96 [Mobility Radeon HD 4650/5165] 
           vendor: Toshiba America Info Systems driver: radeon v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: AMD RV730 (DRM 2.50.0 / 4.15.0-72-generic LLVM 8.0.0) v: 3.3 Mesa 19.0.8 direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio vendor: Toshiba America Info Systems 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Device-2: Advanced Micro Devices [AMD/ATI] RV710/730 HDMI Audio [Radeon HD 4000 series] 
           vendor: Toshiba America Info Systems driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.15.0-72-generic 
Network:   Device-1: Realtek RTL8191SEvB Wireless LAN driver: rtl8192se v: kernel port: 7000 bus ID: 07:00.0 
           IF: wlp7s0 state: up mac: <filter> 
           Device-2: Realtek RTL810xE PCI Express Fast Ethernet vendor: Toshiba America Info Systems driver: r8169 
           v: 2.3LK-NAPI port: 5000 bus ID: 0c:00.0 
           IF: enp12s0 state: down mac: <filter> 
Drives:    Local Storage: total: 465.76 GiB used: 86.65 GiB (18.6%) 
           ID-1: /dev/sda vendor: Fujitsu model: MJA2500BH G2 size: 465.76 GiB 
Partition: ID-1: / size: 318.02 GiB used: 86.65 GiB (27.2%) fs: ext4 dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 46.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 221 Uptime: 1d 2h 05m Memory: 3.72 GiB used: 2.23 GiB (59.9%) Init: systemd runlevel: 5 Compilers: 
           gcc: 7.4.0 clang: 6.0.0-1ubuntu2 Shell: bash v: 4.4.20 inxi: 3.0.32
```

**Comment by davidhealey** [comment]
Yeah the Projucer that comes with HISE was built on a more modern architecture and uses sse4.1, but when you build it yourself on your system sse4.1 isn't available so the resulting binary doesn't require it. Don't ask me why it works this way because it doesn't seem logical to me either :p

The output from the Intel system looks fine but it's good to double check. 

Is the core dump output you posted earlier from the AMD or the Intel machine?

**Comment by toxonic75** [comment]
i posted the one from my AMD machin, but the Intel laptop produces the same output:
```
           PID: 15619 (Projucer)
           UID: 1000 (toxonic)
           GID: 1000 (toxonic)
        Signal: 4 (ILL)
     Timestamp: Mon 2019-12-09 14:42:09 CET (56s ago)
  Command Line: /home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer
    Executable: /home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (toxonic)
       Boot ID: 64783a8561124baf8e6123a076416f97
    Machine ID: f3d85c83fd6e458aba76dbf56f683032
      Hostname: toxonic-Satellite-L500
       Storage: /var/lib/systemd/coredump/core.Projucer.1000.64783a8561124baf8e6123a076416f97.15619.1575898929000000.lz4
       Message: Process 15619 (Projucer) of user 1000 dumped core.
                
                Stack trace of thread 15619:
                #0  0x000000000084e149 n/a (/home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer)
                #1  0x000000000084e229 n/a (/home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer)
                #2  0x0000000000a3ad1d n/a (/home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer)

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer...(no debugging symbols found)...fertig.
[New LWP 15619]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/toxonic/Source Applications/HISE/HISE-scriptnode/tools/projucer/Projucer'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000000000084e149 in __static_initialization_and_destruction_0 ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7f563048b280 (LWP 15619)):
#0  0x000000000084e149 in _Z41__static_initialization_and_destruction_0ii ()
#1  0x000000000084e229 in _GLOBAL__sub_I__ZNK4juce6ColoureqERKS0_ ()
#2  0x0000000000a3ad1d in __libc_csu_init ()
#3  0x00007f562ab81b28 in __libc_start_main (main=0x43938b <main>, argc=1, argv=0x7ffd86548ec8, init=
    0xa3acd0 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd86548eb8) at ../csu/libc-start.c:266
#4  0x000000000040b7c9 in _start ()
```

**Comment by davidhealey** [comment]
Very strange. The only thing that stands out to me is that your graphics card is AMD, but I wouldn't have thought that would have an effect.

Here's something to try. If you build it yourself on your intel machine, does the same binary run on your AMD machine?

**Comment by toxonic75** [comment]
i tried that, and how you might expected, the binary doesn't work on the AMD, when built on the Intel. however, the debugger output differs from those before:
```
           PID: 3791 (Projucer)
           UID: 1000 (toxonic)
           GID: 1000 (toxonic)
        Signal: 4 (ILL)
     Timestamp: Tue 2019-12-10 10:34:21 CET (1min 9s ago)
  Command Line: /home/toxonic/Schreibtisch/Projucer
    Executable: /home/toxonic/Schreibtisch/Projucer
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (toxonic)
       Boot ID: a61a39cbe119453b9e4c2acc7b417c00
    Machine ID: f3d85c83fd6e458aba76dbf56f683032
      Hostname: toxonic-studio
       Storage: /var/lib/systemd/coredump/core.Projucer.1000.a61a39cbe119453b9e4c2acc7b417c00.3791.1575970461000000.lz4
       Message: Process 3791 (Projucer) of user 1000 dumped core.
                
                Stack trace of thread 3791:
                #0  0x00000000007843bd n/a (/home/toxonic/Schreibtisch/Projucer)

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/toxonic/Schreibtisch/Projucer...(no debugging symbols found)...fertig.
[New LWP 3791]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/toxonic/Schreibtisch/Projucer'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000000007843bd in juce::Colour::contrasting(float) const ()
(gdb) thread apply all bt

Thread 1 (Thread 0x7fc8d76a8680 (LWP 3791)):
#0  0x00000000007843bd in juce::Colour::contrasting(float) const ()
#1  0x00000000008951ae in juce::LookAndFeel_V3::LookAndFeel_V3() ()
#2  0x0000000000898d0d in juce::LookAndFeel_V4::LookAndFeel_V4() ()
#3  0x000000000069b00c in ProjucerLookAndFeel::ProjucerLookAndFeel() ()
#4  0x00000000004d375d in ProjucerApplication::ProjucerApplication() ()
#5  0x00000000004dd919 in juce_CreateApplication() ()
#6  0x00000000007775ed in juce::JUCEApplicationBase::main() ()
#7  0x00000000007775ab in juce::JUCEApplicationBase::main(int, char const**) ()
#8  0x00007fc8cf0edb97 in __libc_start_main (main=0x4dd940 <main>, argc=1, argv=0x7ffd3dd3b338, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd3dd3b328) at ../csu/libc-start.c:310
#9  0x00000000004bdf8a in _start ()
(gdb) 
```

**Comment by davidhealey** [comment]
Ok that's good in a way because it confirms that the issue on your laptop is not the same issue as on your desktop. Even though the output is not exactly the same I still think it's sse that's causing the problem here because of this line

> Program terminated with signal SIGILL, Illegal instruction.

I still don't know why it doesn't work on your Intel machine though... maybe @christophhart can shed some light on this.
