### ISSUE TITLE
HISE command line crashes without moduleEnums.xml on export_ci

### ISSUE THREAD

**Issue by KottV** [christophhart/HISE#317]
Hi,

It's great that HISE can be used for headless build. Unfortunately, it crashes when tries (afaik) to generate `.hise\moduleEnums.xml` in home folder. If I run GUI HISE app, then there is `moduleEnums.xml` and it's possible to put it in `.hise\moduleEnums.xml` and command line version works without crash.

Steps to reproduce:
Have a clean profile, eg no `~/.hise`
Set HISE folders with `HISE set_hise_folder` and `HISE set_project_folder`
Export project for CI: `HISE export_ci Presets/Demo.hip -p:VST -a:x86x64 -t:instrument`

```
Thread 1 "HISE Standalone" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff76ba62b in kill () at ../sysdeps/unix/syscall-template.S:120
120     ../sysdeps/unix/syscall-template.S: Directory not empty.
(gdb) bt
#0  0x00007ffff76ba62b in kill () at ../sysdeps/unix/syscall-template.S:120
#1  0x0000000000846419 in hise::Processor::getParentProcessor (this=0x2d9f350, getOwnerSynth=false, assertIfFalse=true) at ../../../../../HISE/hi_dsp/Processor.cpp:330
#2  0x0000000000848ab2 in hise::Processor::isValidAndInitialised (this=0x2d9f350, checkOnAir=false) at ../../../../../HISE/hi_dsp/Processor.cpp:842
#3  0x0000000000845e1a in hise::Processor::setIsOnAir (this=0x2d9f350, shouldBeOnAir=false) at ../../../../../HISE/hi_dsp/Processor.cpp:232
#4  0x000000000084b362 in hise::Chain::Handler::clearAsync (this=0x2da38b0, parentThatShouldBeTakenOffAir=0x2d9f350) at ../../../../../HISE/hi_dsp/ProcessorInterfaces.cpp:233
#5  0x0000000000888f5a in hise::ModulatorSynthGroup::~ModulatorSynthGroup (this=0x2d9f270, __in_chrg=<optimized out>) at ../../../../../HISE/hi_dsp/modules/ModulatorSynthGroup.cpp:876
#6  0x0000000000889094 in hise::ModulatorSynthGroup::~ModulatorSynthGroup (this=0x2d9f270, __in_chrg=<optimized out>) at ../../../../../HISE/hi_dsp/modules/ModulatorSynthGroup.cpp:883
#7  0x0000000000597ef2 in juce::ContainerDeletePolicy<hise::Processor>::destroy (object=0x2d9f350) at ../../../../../HISE/hi_backend/../hi_modules/../hi_scripting/../hi_sampler/../hi_components/../hi_dsp/../hi_core/../JUCE/modules/juce_core/memory/juce_ContainerDeletePolicy.h:54
#8  0x0000000000583774 in juce::ScopedPointer<hise::Processor>::reset (this=0x7fffffffce08) at ../../../../../HISE/hi_backend/../hi_modules/../hi_scripting/../hi_sampler/../hi_components/../hi_dsp/../hi_core/../JUCE/modules/juce_core/memory/juce_ScopedPointer.h:96
#9  0x000000000055bffc in juce::ScopedPointer<hise::Processor>::~ScopedPointer (this=0x7fffffffce08, __in_chrg=<optimized out>)
    at ../../../../../HISE/hi_backend/../hi_modules/../hi_scripting/../hi_sampler/../hi_components/../hi_dsp/../hi_core/../JUCE/modules/juce_core/memory/juce_ScopedPointer.h:54
#10 0x00000000007863e3 in hise::PresetHandler::buildFactory (t=0x2d9ee90, factoryName=...) at ../../../../../HISE/hi_core/hi_core/PresetHandler.cpp:2046
#11 0x0000000000785cf6 in hise::PresetHandler::buildProcessorDataBase (root=0x2cad6f0) at ../../../../../HISE/hi_core/hi_core/PresetHandler.cpp:1995
#12 0x00000000004a335f in hise::BackendRootWindow::BackendRootWindow (this=0x2d9e440, ownerProcessor=0x2c16d10, editorState=...) at ../../../../../HISE/hi_backend/backend/BackendRootWindow.cpp:40
#13 0x000000000047e0e2 in hise::BackendProcessor::createEditor (this=0x2c16d10) at ../../../../../HISE/hi_backend/backend/BackendProcessor.cpp:282
#14 0x0000000000423468 in hise::StandaloneProcessor::createEditor (this=0x2c16580) at ../../../../../HISE/hi_backend/../hi_modules/../hi_scripting/../hi_sampler/../hi_components/../hi_dsp/../hi_core/hi_core/StandaloneProcessor.h:303
#15 0x00000000004a92e0 in hise::CompileExporter::compileFromCommandLine (commandLine=..., pluginFile=...) at ../../../../../HISE/hi_backend/backend/CompileExporter.cpp:267
#16 0x0000000000450953 in HISEStandaloneApplication::initialise (this=0x2c15f70, commandLine=...) at ../../Source/Main.cpp:534
#17 0x00000000017da5c6 in juce::JUCEApplicationBase::initialiseApp (this=0x2c15f70) at ../../../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:297
#18 0x0000000001963768 in juce::JUCEApplication::initialiseApp (this=0x2c15f70) at ../../../../JUCE/modules/juce_gui_basics/application/juce_Application.cpp:92
#19 0x00000000017da481 in juce::JUCEApplicationBase::main () at ../../../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:256
#20 0x00000000017da39a in juce::JUCEApplicationBase::main (argc=6, argv=0x7fffffffd618) at ../../../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
#21 0x00000000004419e3 in main (argc=6, argv=0x7fffffffd618) at ../../Source/Main.cpp:730
```

OS: openSUSE TW, gcc 11.2.1
HISE: development branch `2.1.0-2122-ga9bd04232`

**Comment by davidhealey** [comment]
I get a crash but a different error:

```
terminate called after throwing an instance of 'hise::CommandLineException'
what():  std::exception
Aborted```

**Comment by KottV** [comment]
Thanks, @davidhealey 
If I execute HISE outside GDB I get the same exception error.
